DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    user_email TEXT,
    user_password TEXT,
    user_id TEXT UNIQUE,
    user_thumbnail TEXT,
    user_dark_mode BOOLEAN DEFAULT FALSE
);